name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: valid test
        run: |
          ls
          ./html5.sh test5/ok*.html
          for fname in test5/ng*.html; do if ./html5.sh ${fname}; then exit 1; fi; done
          ./hreftgt.sh testht/ok*.html
          for fname in testht/ng*.html; do echo ${fname}; if ./hreftgt.sh ${fname}; then exit 1; fi; done



